### PR TITLE
enhanced the UI of the FAQ section

### PR DESCRIPTION
**Pull request by AADESHak007**
## Fixes Issue

This PR fixes the following issues:

I have enhanced the UI of the FAQ section  and also changed the layout of the social media section  adding animation  to it was not a better option  as it could deteriorate the motive of adding those posts

## Changes proposed

Here comes all the changes proposed through this PR
You will definitely love the change as I have followed the color scheme  of the whole website and kept it simple 

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots and video
AFTER :
Screenshot 2024-10-03 122224

BEFORE :
Screenshot 2024-10-02 213100

### CODE REVIEW

**Comment by AADESHak007** [comment]
@PranavBarthwal could you please review it

**Comment by PranavBarthwal** [comment]
lgtm, @pradeeptosarkar & @SahilTyagii thoughts?

**Comment by AADESHak007** [comment]
@PranavBarthwal in the meantime could you provide me with our thoughts in this .

**Comment by pradeeptosarkar** [comment]
gtg @PranavBarthwal

**Review by pradeeptosarkar — APPROVED** [review]

**Review by PranavBarthwal — APPROVED** [review]

**Review by PranavBarthwal — APPROVED** [review]

**Pull request merged**
