### PR TITLE
added cards in Chapter

### PR DESCRIPTION
**Pull request by kmahesh18**
image
uploaded cards to chapter

### CODE REVIEW

**Comment by kmahesh18** [comment]
@namespace-admin check the pr

**Comment by pradeeptosarkar** [comment]
@kmahesh18 will merge after a few days as a major update is underway. Thanks for contributing.

**Review by pradeeptosarkar — APPROVED** [review]

**Comment by kmahesh18** [comment]
are there any more issues to merge

**Comment by pradeeptosarkar** [comment]
> are there any more issues to merge

yes

**Comment by kmahesh18** [comment]
> > are there any more issues to merge
> 
> yes

Please mention the issue .. I can solve it

**Comment by pradeeptosarkar** [comment]
closing due to new version of website released

**Pull request closed without merging**
